document.write("<table cellspacing='2' border='1px solid black'>");
document.write("<tr>");
document.write("<td>apCodename</td>");
document.write("<td>"+ navigator.appCodeName +"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>Navigator Name</td>");
document.write("<td>"+ navigator.appName +"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>Navigator Version</td>");
document.write("<td>"+ navigator.appVersion +"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>Cookies</td>");
document.write("<td>"+ navigator.cookieEnabled +"</td>"); 
document.write("</tr>");
document.write("<tr>");
document.write("<td>Plataform</td>");
document.write("<td>"+ navigator.platform +"</td>"); 
document.write("</tr>");
document.write("<tr>");
document.write("<td>Agent</td>");
document.write("<td>"+ navigator.userAgent +"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>Languague</td>");
document.write("<td>"+ navigator.language+"</td>");
document.write("</tr>");
document.write("</table>");